### ISSUE TITLE
Things that need to be fixed

### ISSUE THREAD

**Issue by dudik** [dudik/blockit#1]
This is a small TODO list for myself. The extension is usable, but some things need to be fixed/implemented. Feel free to open new issues for other problems you encounter.

- [x] Fix memory leaks (forgot to free memory...)
- [x] Start ars automatically if it's not running
- [x] Fix infinite loop that appears when ars is not running
- [x] Add some form of GUI for list management, enable/disable blocking for specific sites etc.
- [ ] Error handling
- [ ] More sophisticated resource type matching
- [x] Engine serialization
- [x] Wait for all resources to load (cosmetic filtering sometimes doesn't work) (fixed, also CSP problems, but for now requires javascript)

**Comment by aartaka** [comment]
- [ ] Support [GNU Makefile conventions](https://www.gnu.org/prep/standards/html_node/Makefile-Conventions.html) (especially "DESDIR" and "Directory variables") in the Makefile so that blockit is easier to package and install on a range of systems :)
